# Generated by Django 3.0.4 on 2020-04-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fuser',
        ),
    ]
