# Generated by Django 3.0.4 on 2020-04-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200403_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuser',
            options={'verbose_name': '사용자 모임', 'verbose_name_plural': '사용자 모임'},
        ),
    ]
