# Generated by Django 3.0.4 on 2020-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200403_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebUSer',
        ),
        migrations.AddField(
            model_name='fuser',
            name='useremail',
            field=models.EmailField(default='undefine@example.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
