# Generated by Django 3.0.4 on 2020-04-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200403_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.AlterModelOptions(
            name='fuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='fuser',
            table=None,
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
