# Generated by Django 3.0.4 on 2020-04-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200405_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuser',
            options={'verbose_name': '사용자 모임', 'verbose_name_plural': '사용자 모임'},
        ),
        migrations.AlterModelTable(
            name='fuser',
            table='user_define_fuser_table',
        ),
    ]
